project_id = "ljbsxehdiskqggpssuay"

[functions.nylo-chat]
verify_jwt = false

[functions.generate-recurring-bills]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-notify]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.notify-plan-change]
verify_jwt = false

[functions.check-expired-plans]
verify_jwt = false
